### ISSUE TITLE
Implement a component for user references

### ISSUE THREAD

**Issue by Harshil-Jani** [block-core/blockcore-notes#138]
With the completion of #136 we can now easily refer the users whom we follow. But we need to remember their ID's which is tough to do. It's better to have a component which shows us all the available users from our follow list and also filter them as we type characters next to `@`.

**Comment by dangershony** [comment]
You mean look at users we fetched events for in the past?

**Comment by sondreb** [comment]
The search component on the top is suppose to be able to do searches like that, but it appears to be a bit buggy right now. We need such a service yes, but it's probably made partially already for the search component.

**Comment by Harshil-Jani** [comment]
It's different from the global search. This is restricted to the editor component just to put forward the mentions. 

But that's actually a good idea and If you think the current state of editor (refer video below) is working correctly, We can implement the same for the searchbar and it would work in similar way.


https://github.com/block-core/blockcore-notes/assets/79367883/ac8ea18f-afd9-4a3c-aecd-96420b626357

**Comment by dangershony** [comment]
> We can implement the same for the searchbar and it would work in similar way.  

sounds good to me
