### ISSUE TITLE
TypeError: globalThis.nostr is undefined

### ISSUE THREAD

**Issue by cblp** [block-core/blockcore-notes#149]
When I try to reply to a post

**Comment by sondreb** [comment]
Which browser extension you using for your key?

**Comment by cblp** [comment]
Firefox

**Comment by cblp** [comment]
I'm not sure if I entered the private key.

**Comment by sondreb** [comment]
> Firefox

Blockcore Notes doesn't support FireFox. Behind FireFox is a company (Mozilla) that is against free speech and want to oppress and suppress people who have ideas their management don't support. Please see blog post from their former CEO regarding this.

Additionally Mozilla attempted to hinder DID to become a W3C specification, which is extremely hostile against freedom of speech and individual data ownership to individuals and not corporations.

Anyone who wants to add support for FireFox are free to make a pull request, but the main part is probably the Service Worker which uses the Manifest v3 format and the code is probably not fully compatible with FireFox.
