### ISSUE TITLE
 The buttons in the settings section must be responsive

### ISSUE THREAD

**Issue by miladsoft** [block-core/blockcore-notes#23]
The buttons in the settings section must be responsive

![image](https://user-images.githubusercontent.com/6504337/210154405-5dcad98d-c3ae-4023-8f81-5b8026e7774e.png)

**Comment by sondreb** [comment]
On medium screen:

![image](https://user-images.githubusercontent.com/309938/210154970-0598c74e-63a0-4640-8429-41b33067a2f1.png)

On small screen:

![image](https://user-images.githubusercontent.com/309938/210154978-fa7507ba-c89a-4912-ad5b-c29b47d6e34a.png)
