### ISSUE TITLE
Support for public keys that have a nostr: prefix/uri

### ISSUE THREAD

**Issue by hegjon** [block-core/blockcore-notes#81]
For example https://cowdle.gg/ publish their public key as following:

```
nostr:npub136ljffk35zaknaauukrrlmpgdle6p6a0mlcw383w6gvas0epjguqc8mumr
```

Pasting this string into add a person does nothing, and I don't get an error messages.

**Comment by sondreb** [comment]
The Blockcore Wallet extension will add support for parsing links like that, but obviously if you copy and paste into Blockcore Notes it should work.
